name: first schedule example
on:
  schedule:
    - cron: '*/1 * * * *'
    
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will run @ $(date)"
